CREATE TABLE customer (
        C_CUSTKEY       INTEGER NOT NULL,
        C_NAME          STRING NOT NULL,
        C_ADDRESS       STRING NOT NULL,
        C_CITY          STRING NOT NULL,
        C_NATION        STRING NOT NULL,
        C_REGION        STRING NOT NULL,
        C_PHONE         STRING NOT NULL,
        C_MKTSEGMENT    STRING NOT NULL
);
CREATE INDEX customer_index ON customer(C_NATION, C_REGION, C_CITY);

CREATE TABLE lineorder (
    LO_ORDERKEY             LONG NOT NULL,
    LO_LINENUMBER           INTEGER NOT NULL,
    LO_CUSTKEY              INTEGER NOT NULL,
    LO_PARTKEY              INTEGER NOT NULL,
    LO_SUPPKEY              INTEGER NOT NULL,
    LO_ORDERDATE            DATE NOT NULL,
    LO_ORDERPRIORITY        STRING NOT NULL,
    LO_SHIPPRIORITY         INTEGER NOT NULL,
    LO_QUANTITY             INTEGER NOT NULL,
    LO_EXTENDEDPRICE        INTEGER NOT NULL,
    LO_ORDTOTALPRICE        INTEGER NOT NULL,
    LO_DISCOUNT             INTEGER NOT NULL,
    LO_REVENUE              INTEGER NOT NULL,
    LO_SUPPLYCOST           INTEGER NOT NULL,
    LO_TAX                  INTEGER NOT NULL,
    LO_COMMITDATE           DATE NOT NULL,
    LO_SHIPMODE             STRING NOT NULL
);
CREATE INDEX lineorder_index ON lineorder(LO_ORDERDATE, LO_ORDERKEY);

CREATE TABLE supplier (
        S_SUPPKEY       INTEGER NOT NULL,
        S_NAME          STRING NOT NULL,
        S_ADDRESS       STRING NOT NULL,
        S_CITY          STRING NOT NULL,
        S_NATION        STRING NOT NULL,
        S_REGION        STRING NOT NULL,
        S_PHONE         STRING NOT NULL
);
CREATE INDEX supplier_index ON supplier(S_NATION, S_REGION, S_CITY);

CREATE TABLE part (
        P_PARTKEY       INTEGER NOT NULL,
        P_NAME          STRING NOT NULL,
        P_MFGR          STRING NOT NULL,
        P_CATEGORY      STRING NOT NULL,
        P_BRAND         STRING NOT NULL,
        P_COLOR         STRING NOT NULL,
        P_TYPE          STRING NOT NULL,
        P_SIZE          INTEGER NOT NULL,
        P_CONTAINER     STRING NOT NULL
);
CREATE INDEX part_index ON part(P_CATEGORY, P_BRAND, P_MFGR);